# Generated by Django 5.1 on 2024-11-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('Client', 'Client'), ('Saloon Staff', 'Saloon Staff'), ('Admin', 'Admin'), ('Shop', 'Shop')], max_length=100, null=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('email_token', models.CharField(blank=True, max_length=10, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('availability_interval', models.CharField(blank=True, choices=[('1 hour', '1 hour'), ('6 hours', '6 hours'), ('12 hours', '12 hours'), ('8 hours', '8 hours'), ('24 hours', '24 hours'), ('48 hours', '48 hours')], default='1 hour', max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=30, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
