# Generated by Django 5.1 on 2024-11-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopavailability',
            old_name='closed',
            new_name='closed_time',
        ),
        migrations.RenameField(
            model_name='shopavailability',
            old_name='open',
            new_name='open_time',
        ),
    ]
