# Generated by Django 5.1 on 2024-11-27 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('shop', '0001_initial'),
        ('slots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=200, null=True)),
                ('service_type', models.CharField(blank=True, max_length=200, null=True)),
                ('home_service', models.BooleanField(blank=True, default=False, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booking_time', models.TimeField(blank=True, null=True)),
                ('re_scheduled', models.BooleanField(default=False)),
                ('booking_rescheduled_at', models.DateTimeField(blank=True, null=True)),
                ('split', models.BooleanField(blank=True, default=False, null=True)),
                ('booking_split_from', models.TimeField(blank=True, null=True)),
                ('booking_split_to', models.TimeField(blank=True, null=True)),
                ('amount_to_pay', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_price', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('confirm_payment', models.BooleanField(default=False)),
                ('is_gift', models.BooleanField(default=False)),
                ('actual_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rescheduled', 'Rescheduled'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Started', 'Started'), ('Ongoing', 'Ongoing'), ('Review', 'Review'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=255, null=True)),
                ('booking_start', models.DateTimeField(blank=True, null=True)),
                ('booking_end', models.DateTimeField(blank=True, null=True)),
                ('booking_approved_at', models.DateTimeField(blank=True, null=True)),
                ('booking_declined_at', models.DateTimeField(blank=True, null=True)),
                ('booking_cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_staffs', to='shop.shopstaff')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_service_bookings', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_package', to='shop.shoppackage')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_chat_rooms', to='chats.privatechatroom')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_service_bookings', to='shop.shopservice')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_bookings', to='shop.shop')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_slot', to='slots.staffslot')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('report', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_ratings', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='GiftBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_bookings', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='WalkInBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_in_bookings', to='bookings.booking')),
            ],
        ),
    ]
